### ISSUE TITLE
Add a Crayola struct that returns UIColors

### ISSUE THREAD

**Issue by jpmcglone** [FlowDK/FlowDK#1]
Add a Crayola struct that returns UIColors

UIColor.swift

```
struct Crayola {
  static var red = UIColor(0xED0A3F)
  // and so on
}
```

Example usage:
```
myLabel.textColor = Crayola.red
```

The full list of crayola colors can be found here:
https://en.wikipedia.org/wiki/List_of_Crayola_crayon_colors

- [x] Add class

- [ ] Write tests

- [x] Run pod install

- [ ] Tests pass

We will consider making `Crayola` its own repository, but for now, make it part of FlowDK!

**Comment by thiskevinwang** [comment]
Moved tests to https://github.com/FlowDK/FlowDK/issues/8
